function varargout = PhyscistInput2(varargin)
% PHYSCISTINPUT2 M-file for PhyscistInput2.fig
%      PHYSCISTINPUT2, by itself, creates a new PHYSCISTINPUT2 or raises the existing
%      singleton*.
%
%      H = PHYSCISTINPUT2 returns the handle to a new PHYSCISTINPUT2 or the handle to
%      the existing singleton*.
%
%      PHYSCISTINPUT2('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in PHYSCISTINPUT2.M with the given input arguments.
%
%      PHYSCISTINPUT2('Property','Value',...) creates a new PHYSCISTINPUT2 or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before PhyscistInput2_OpeningFunction gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to PhyscistInput2_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help PhyscistInput2

% Last Modified by GUIDE v2.5 18-Mar-2013 13:13:25

% Begin initialization code - DO NOT EDIT

% This was generated by guide for list of physiicsts using popup menu.

gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @PhyscistInput2_OpeningFcn, ...
                   'gui_OutputFcn',  @PhyscistInput2_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before PhyscistInput2 is made visible.
function PhyscistInput2_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to PhyscistInput2 (see VARARGIN)

% Choose default command line output for PhyscistInput2
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes PhyscistInput2 wait for user response (see UIRESUME)

uiwait(handles.figure1);


% --- Outputs from this function are returned to the command line.
function varargout = PhyscistInput2_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;

% delete the handles now

delete(handles.figure1);

% --- Executes on selection change in popupmenu1.
function popupmenu1_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = get(hObject,'String') returns popupmenu1 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu1

% set the initial list of physicist

% test={'a';'b'};
% 
% % physicists='Richard Short|Alison Gray|Armia George|Jarrad Beggt'
% % Philip Vial|Sankar Arumugam|Satya Rajapakse|Shrikant Deshpande| ...
% % Tania Erven|Aitang Xing|Tony Young|Vinod Nelson|Virendra Patel|....
% % Gary Goozee'
% 
% set(hObject,'String',test);

index=get(hObject,'Value');

string_list=get(hObject,'String');

selected_physicist=string_list{index};

handles.output=selected_physicist;

% Update handles structure
guidata(hObject, handles);

% Use UIRESUME instead of delete because the OutputFcn needs
% to get the updated handles structure.
uiresume(handles.figure1);


% --- Executes during object creation, after setting all properties.
function popupmenu1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.

physicists={'Richard Short';'Alison Gray';'Armia George';'Jarrad Beggt';'Philip Vial';'Sankar Arumugam';'Satya Rajapakse';'Shrikant Deshpande';'Tania Erven';'Aitang Xing';'Tony Young';'Vinod Nelson';'Virendra Patel';'Gary Goozee'};

set(hObject,'String',physicists);



if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



% --- Executes when user attempts to close figure1.
function figure1_CloseRequestFcn(hObject, eventdata, handles)
% hObject    handle to figure1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hint: delete(hObject) closes the figure

if isequal(get(handles.figure1, 'waitstatus'), 'waiting')
    % The GUI is still in UIWAIT, us UIRESUME
    uiresume(handles.figure1);
else
    % The GUI is no longer waiting, just close it
    delete(handles.figure1);
end




% --- Executes during object deletion, before destroying properties.
function popupmenu1_DeleteFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


